geometry_msgs/Pose[]     origin #if empty use tf, if less origin then the last origin is used for the left overs...
geometry_msgs/Pose[]     target
int32                    scale  # between 1..n  nxn pixels get to one pixel
---
float64[]                length
nav_msgs/Path[]          path
